
version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_hcd
    outputs:
      highly_sensitive:
        cohort: output/input_hcd.csv
        
  run_model:
    run: r:latest analysis/summary_output_hcd.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        analysis: output/*